openapi: 3.0.3
info:
  version: '0.1.0'
  title: 'household expenses API'
  # https://swagger.io/specification/
  description: |
    household expenses API
servers:
  - url: https://localhost:8080/
paths:
  # expense
  /expenses:
    get:
      tags:
        - 'expenses'
      summary: '支出の一覧取得'
      description: '支出一覧を返す'
      responses:
        '200':
          description: '正常'
          content:
            application/vnd.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/expenseResponseDto'

  # category
  /categories:
    get:
      tags:
        - 'categories'
      summary: 'カテゴリーの一覧取得'
      description: 'カテゴリー一覧を返す'
      responses:
        '200':
          description: '正常'
          content:
            application/vnd.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/categoryResponseDto'

components:
  schemas:
    expenseResponseDto:
      type: object
      required:
        - id
        - category_name
        - name
        - price
        - memo
        - date
        # TODO: front が使いやすい形式に整形して返すか要検討
        - repeatable_month
        - repeatable_count
      properties:
        id:
          type: integer
          example: 1
        category_name:
          type: string
          example: '食費'
        name:
          type: string
          example: '粉ミルク'
        price:
          type: integer
          example: 500
        memo:
          type: string
          example: '200gの缶のもの'
          nullable: true
        date:
          type: string
          format: date
          example: 2022-11-22
        repeatable_month:
          type: integer
          description: |
            繰り返しの予定の何ヶ月ごとかを表すデータ
            1ヶ月に1回だと **1** となる
          example: 1
          nullable: true
        repeatable_count:
          type: integer
          description: |
            繰り返しの予定の月あたりの回数を表すデータ
            1ヶ月に1回だと **1** となる
          example: 1
          nullable: true

    categoryResponseDto:
      type: object
      required:
        - id
        - name
        - rank
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: '食費'
        rank:
          type: integer
          example: 1
