services:
  postgres:
    image: postgres:12.12
    container_name: household-expenses-postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: household-expenses
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
